//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuantaLabsDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashCreditMain
    {
        public string PSCName { get; set; }
        public int BillNo { get; set; }
        public string BillType { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<double> AmtReceived { get; set; }
        public string Modeofpay { get; set; }
        public string BankName { get; set; }
        public string Remark { get; set; }
        public string BillNotes { get; set; }
        public string Discount { get; set; }
        public Nullable<double> NetPayment { get; set; }
        public string PatRegNo { get; set; }
        public string patName { get; set; }
        public Nullable<int> PatAge { get; set; }
        public string PatGender { get; set; }
        public string Pattest { get; set; }
        public Nullable<int> companyid { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<double> AmtPaid { get; set; }
        public Nullable<double> Balance { get; set; }
        public string username { get; set; }
        public Nullable<System.DateTime> billTime { get; set; }
        public Nullable<double> Othercharges { get; set; }
        public string City { get; set; }
        public string AccNo { get; set; }
        public string ChqNo { get; set; }
        public Nullable<System.DateTime> ChqDate { get; set; }
        public string CCNo { get; set; }
        public string CCName { get; set; }
        public string Cardtype { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string AmtDepBank { get; set; }
        public Nullable<bool> VerifyFlag { get; set; }
    }
}
