//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuantaLabsDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactinformationTemp
    {
        public int Id { get; set; }
        public Nullable<int> RegNo { get; set; }
        public string Iopd { get; set; }
        public Nullable<decimal> companyid { get; set; }
    }
}
