//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuantaLabsDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactInformation
    {
        public int SrNo { get; set; }
        public int C_ID { get; set; }
        public string RegNo { get; set; }
        public string IOPD { get; set; }
        public Nullable<System.DateTime> DateOfEntry { get; set; }
        public string intial { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string sex { get; set; }
        public Nullable<int> Age { get; set; }
        public string MDY { get; set; }
        public string RefDr { get; set; }
        public string Check_Flag { get; set; }
        public string Tests { get; set; }
        public string TestsWithGroups { get; set; }
        public string Default_TestResult { get; set; }
        public string Technician_Name { get; set; }
        public Nullable<bool> Flag_Tech { get; set; }
        public Nullable<bool> Flag_CollCenter { get; set; }
        public Nullable<bool> PrintFlag { get; set; }
        public Nullable<System.DateTime> Reportdate { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<System.DateTime> exam_date { get; set; }
        public string Report_time { get; set; }
        public string exam_time { get; set; }
        public Nullable<bool> flag { get; set; }
        public string PatientPhoneNo { get; set; }
        public string PatientCity { get; set; }
        public string patient_addr { get; set; }
        public Nullable<bool> emergencyflag { get; set; }
        public Nullable<int> xa { get; set; }
        public Nullable<int> xr { get; set; }
        public Nullable<int> ec { get; set; }
        public Nullable<int> mr { get; set; }
        public Nullable<int> ct { get; set; }
        public Nullable<int> se { get; set; }
        public Nullable<int> pt { get; set; }
        public Nullable<bool> cbcflag { get; set; }
        public string graph { get; set; }
        public Nullable<decimal> CompanyId { get; set; }
        public string Dr_Code { get; set; }
        public string Tech_Code { get; set; }
        public string Coll_Code { get; set; }
        public string CompCode { get; set; }
        public string EmailID { get; set; }
        public string DocName { get; set; }
        public string wbc { get; set; }
        public string rbc { get; set; }
        public string plt { get; set; }
        public string plt1 { get; set; }
        public string coulter { get; set; }
        public Nullable<double> TestCharges { get; set; }
        public Nullable<decimal> HospitalID { get; set; }
        public string WardNo { get; set; }
        public string BedNo { get; set; }
        public string WDeptNo { get; set; }
        public Nullable<int> PR { get; set; }
        public Nullable<decimal> Rcat { get; set; }
        public Nullable<decimal> pat_id { get; set; }
        public Nullable<decimal> subpat_id { get; set; }
        public string roomnum { get; set; }
        public string bednum { get; set; }
        public Nullable<bool> Pay { get; set; }
        public string SampleID { get; set; }
        public string Collection_Center { get; set; }
        public string Username { get; set; }
        public string Usertype { get; set; }
        public string SampleType { get; set; }
        public string SampleStatus { get; set; }
        public string Remark { get; set; }
        public string SampleNotes { get; set; }
        public string PSCRegNo { get; set; }
        public string VialID { get; set; }
        public string Clinical_History { get; set; }
        public Nullable<System.DateTime> RegistratonDateTime { get; set; }
        public string ReportNo { get; set; }
        public string CourierDetails { get; set; }
        public string compname { get; set; }
        public string deptNo { get; set; }
        public string FinancialYearID { get; set; }
        public string PePatID { get; set; }
        public Nullable<int> OPDNo { get; set; }
        public Nullable<int> IPDNo { get; set; }
        public string TelNo { get; set; }
        public string Note { get; set; }
        public string OrderPriority { get; set; }
        public Nullable<decimal> billno { get; set; }
        public Nullable<bool> byWhom { get; set; }
        public Nullable<double> AmountPaid { get; set; }
        public Nullable<double> Discount { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<decimal> PathNo { get; set; }
        public Nullable<decimal> RadNo { get; set; }
        public Nullable<decimal> OtherNo { get; set; }
        public string PUserName { get; set; }
        public string PPassword { get; set; }
        public Nullable<bool> PackageFlag { get; set; }
        public Nullable<int> Labno { get; set; }
        public Nullable<int> Packageid { get; set; }
        public Nullable<int> unitid { get; set; }
        public Nullable<bool> deleteflag { get; set; }
        public Nullable<bool> SampleFlag { get; set; }
        public Nullable<int> HivNo { get; set; }
        public Nullable<int> IsCancel { get; set; }
        public Nullable<System.DateTime> CancelledDatetime { get; set; }
        public string HivType { get; set; }
        public Nullable<int> ConsultantId { get; set; }
        public Nullable<bool> AuthorisedFlag { get; set; }
        public string Authusername { get; set; }
        public Nullable<System.DateTime> AuthDateTime { get; set; }
    }
}
