//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuantaLabsDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailTestReport
    {
        public Nullable<int> SrNo { get; set; }
        public int Regno { get; set; }
        public string IOPD { get; set; }
        public string Sex { get; set; }
        public string RefDr { get; set; }
        public Nullable<System.DateTime> Dateofentry { get; set; }
        public string Name { get; set; }
        public string TestName { get; set; }
        public Nullable<double> PaidAmount { get; set; }
        public Nullable<double> BillAmount { get; set; }
        public bool flagvisible { get; set; }
        public string TLCODE { get; set; }
        public Nullable<int> companyid { get; set; }
    }
}
