//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuantaLabsDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Help_TestMaster
    {
        public int SrNo { get; set; }
        public string HelpTest { get; set; }
        public string TlCode { get; set; }
        public string TestCode { get; set; }
        public string UserName { get; set; }
        public Nullable<int> CompanyId { get; set; }
    }
}
