//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuantaLabsDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientWReagentReportAlter
    {
        public string ItemName { get; set; }
        public string Inject1 { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string TestName { get; set; }
        public Nullable<int> ItemCode { get; set; }
        public string IOPD { get; set; }
        public Nullable<int> Regno { get; set; }
        public string TransType { get; set; }
        public Nullable<double> Unit { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public int TransID { get; set; }
        public string TestCode { get; set; }
        public Nullable<decimal> CompanyId { get; set; }
        public Nullable<double> Rate { get; set; }
    }
}
