//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuantaLabsDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_TestcodeTestname
    {
        public string HCode { get; set; }
        public string Heading { get; set; }
        public string TLCode { get; set; }
        public string Title { get; set; }
        public string TestCode { get; set; }
        public string TestName { get; set; }
        public string Inject1 { get; set; }
        public string ReportHeader { get; set; }
        public Nullable<int> startline { get; set; }
    }
}
