//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuantaLabsDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_ContactInformation
    {
        public string Inject1 { get; set; }
        public string heading { get; set; }
        public Nullable<int> startline { get; set; }
        public int SrNo { get; set; }
        public string RegNo { get; set; }
        public decimal IOPD { get; set; }
        public string DateOfEntry { get; set; }
        public Nullable<System.DateTime> intial { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string sex { get; set; }
        public string Age { get; set; }
        public Nullable<int> MDY { get; set; }
        public string RefDr { get; set; }
        public string Check_Flag { get; set; }
        public string Tests { get; set; }
        public string TestsWithGroups { get; set; }
        public string Default_TestResult { get; set; }
        public string Technician_Name { get; set; }
        public string Flag_Tech { get; set; }
        public Nullable<bool> Collection_Center { get; set; }
        public Nullable<bool> Flag_CollCenter { get; set; }
        public bool PrintFlag { get; set; }
        public Nullable<System.DateTime> Reportdate { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<System.DateTime> exam_date { get; set; }
        public string Report_time { get; set; }
        public string exam_time { get; set; }
        public Nullable<bool> flag { get; set; }
        public string PatientPhoneNo { get; set; }
        public string PatientCity { get; set; }
        public string patient_addr { get; set; }
        public Nullable<decimal> PePatID { get; set; }
        public bool emergencyflag { get; set; }
        public Nullable<int> xa { get; set; }
        public Nullable<int> xr { get; set; }
        public Nullable<int> ec { get; set; }
        public Nullable<int> mr { get; set; }
        public Nullable<int> ct { get; set; }
        public Nullable<int> se { get; set; }
        public Nullable<int> pt { get; set; }
        public bool cbcflag { get; set; }
        public string graph { get; set; }
        public Nullable<decimal> CompanyId { get; set; }
        public string Dr_Code { get; set; }
        public string Tech_Code { get; set; }
        public string Coll_Code { get; set; }
        public string CompCode { get; set; }
        public string FinancialYearID { get; set; }
        public string EmailID { get; set; }
        public string DocName { get; set; }
        public string wbc { get; set; }
        public string rbc { get; set; }
        public string plt { get; set; }
        public string plt1 { get; set; }
        public string coulter { get; set; }
        public Nullable<double> TestCharges { get; set; }
        public Nullable<decimal> SampleID { get; set; }
        public string HospitalID { get; set; }
        public string WardNo { get; set; }
        public string BedNo { get; set; }
        public Nullable<int> WDeptNo { get; set; }
        public Nullable<decimal> PR { get; set; }
        public Nullable<decimal> Rcat { get; set; }
        public Nullable<decimal> pat_id { get; set; }
        public string subpat_id { get; set; }
        public Nullable<decimal> roomnum { get; set; }
        public Nullable<decimal> bednum { get; set; }
        public Nullable<bool> IPDNo { get; set; }
        public string Pay { get; set; }
        public string DrName { get; set; }
    }
}
