//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuantaLabsDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rpt_PrintBarCode
    {
        public string Patient_Name { get; set; }
        public string VialID { get; set; }
        public string TestCodes { get; set; }
        public string RegNo { get; set; }
        public string Scodes { get; set; }
        public Nullable<int> companyid { get; set; }
        public string TestNames { get; set; }
        public string SampleType { get; set; }
    }
}
