//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuantaLabsDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleMaster
    {
        public int sampleid { get; set; }
        public string Sampletype { get; set; }
        public Nullable<int> companyid { get; set; }
        public string username { get; set; }
    }
}
