//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuantaLabsDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Title
    {
        public decimal TitleID { get; set; }
        public string Title1 { get; set; }
        public string TLCode { get; set; }
        public string HCode { get; set; }
        public string Singleformat { get; set; }
        public string NormalValueNew { get; set; }
        public string NormalValueGeneral { get; set; }
        public Nullable<double> TestRate { get; set; }
        public string Sampletype { get; set; }
        public string TextMemo { get; set; }
        public string TestResult { get; set; }
        public Nullable<System.DateTime> Dateofentry { get; set; }
        public string TestResult_text { get; set; }
        public string TestResult_memo { get; set; }
        public string TestMethod_temp { get; set; }
        public string DefaultResult { get; set; }
        public string DefaultResultList { get; set; }
        public Nullable<int> ORDNO { get; set; }
        public string SpecialNote { get; set; }
        public string DefaultTestMethod { get; set; }
        public Nullable<int> Days { get; set; }
        public string scode { get; set; }
        public Nullable<int> testrate1 { get; set; }
        public Nullable<bool> Change_Flag { get; set; }
        public Nullable<bool> add_flag { get; set; }
        public Nullable<bool> cflag { get; set; }
        public Nullable<decimal> Company_Id { get; set; }
        public Nullable<bool> NumericFlag { get; set; }
        public string MachineName { get; set; }
        public string Temp { get; set; }
        public string Schedule { get; set; }
        public Nullable<int> graphflag { get; set; }
        public Nullable<int> companyid { get; set; }
        public Nullable<bool> TResultFlag { get; set; }
        public string username { get; set; }
        public string PreparationTime { get; set; }
        public string SpecificInstruction { get; set; }
        public string HCPCSCode { get; set; }
        public string CPTCode { get; set; }
        public string cghscode { get; set; }
    }
}
