//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuantaLabsDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPatientDiagnosi
    {
        public string ReportNo { get; set; }
        public string intial { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> Date_Of_Entry { get; set; }
        public string diaglcode { get; set; }
        public string diagllcode { get; set; }
        public string diaglllcode { get; set; }
        public string diagvcode { get; set; }
        public string dia_code { get; set; }
        public string site_code { get; set; }
        public string reg_code { get; set; }
        public decimal r_no { get; set; }
        public string descrip { get; set; }
        public string RefDr { get; set; }
    }
}
