//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuantaLabsDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewShowMemo
    {
        public decimal RegNo { get; set; }
        public string IOPD { get; set; }
        public string TlCode { get; set; }
        public string TextMemo { get; set; }
        public string TestCode { get; set; }
    }
}
