//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuantaLabsDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Concatetest
    {
        public int C_ID { get; set; }
        public Nullable<decimal> CompanyId { get; set; }
        public string PePatID { get; set; }
        public Nullable<int> OPDNo { get; set; }
        public Nullable<int> IPDNo { get; set; }
        public Nullable<int> Labno { get; set; }
        public Nullable<double> TestCharges { get; set; }
        public string Result { get; set; }
        public string RequestedTest { get; set; }
    }
}
