//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuantaLabsDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Panic
    {
        public string RegNo { get; set; }
        public string IOPD { get; set; }
        public string intial { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string sex { get; set; }
        public Nullable<int> Age { get; set; }
        public string MDY { get; set; }
        public Nullable<System.DateTime> exam_date { get; set; }
        public string exam_time { get; set; }
        public string TestResult_Format { get; set; }
        public string unit { get; set; }
        public string tname { get; set; }
        public Nullable<decimal> testordno { get; set; }
        public Nullable<System.DateTime> Reportdate { get; set; }
        public Nullable<System.DateTime> DateOfEntry { get; set; }
        public string testmethod { get; set; }
        public string GroupsForFormat { get; set; }
        public Nullable<System.DateTime> Report_Date { get; set; }
        public Nullable<System.DateTime> RegistratonDateTime { get; set; }
        public string DocName { get; set; }
        public string Title { get; set; }
        public string TLCode { get; set; }
        public string testname { get; set; }
        public string AttachFilePath { get; set; }
        public string TestMethod_temp { get; set; }
        public string Coll_Code { get; set; }
        public string VialID { get; set; }
        public Nullable<int> Titleordno { get; set; }
        public Nullable<bool> cflag { get; set; }
        public string Singleformat { get; set; }
        public string TestCode { get; set; }
        public string GroupCode { get; set; }
        public string dr_name { get; set; }
        public Nullable<decimal> CompanyId { get; set; }
        public string Remarks { get; set; }
        public string RefDr { get; set; }
        public Nullable<bool> remarkflag { get; set; }
        public string SampleType { get; set; }
        public string compname { get; set; }
        public string RangeFlag { get; set; }
        public Nullable<int> compid { get; set; }
        public string PanicValue { get; set; }
    }
}
