//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuantaLabsDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_RptRejectTestReport
    {
        public int C_ID { get; set; }
        public string RegNo { get; set; }
        public string IOPD { get; set; }
        public string intial { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string sex { get; set; }
        public Nullable<int> Age { get; set; }
        public string MDY { get; set; }
        public string PePatID { get; set; }
        public string status { get; set; }
        public string Title { get; set; }
        public string MainDept { get; set; }
        public Nullable<decimal> CompanyId { get; set; }
        public string tlcode { get; set; }
        public Nullable<System.DateTime> exam_date { get; set; }
    }
}
