//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuantaLabsDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_rpt_PatientWiseRate
    {
        public string RegNo { get; set; }
        public string Heading { get; set; }
        public string SampleStatus { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string MainDept { get; set; }
        public string DAATE { get; set; }
        public Nullable<double> TestRate { get; set; }
    }
}
