//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuantaLabsDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_referbydoctor
    {
        public string MainDept { get; set; }
        public string RegNo { get; set; }
        public string IOPD { get; set; }
        public string intial { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Dr_Code { get; set; }
        public string Title { get; set; }
        public string TLCode { get; set; }
        public int C_ID { get; set; }
        public string DocName { get; set; }
        public Nullable<int> OPDNo { get; set; }
        public Nullable<int> IPDNo { get; set; }
        public Nullable<double> TestRate { get; set; }
        public Nullable<System.DateTime> RegistratonDateTime { get; set; }
        public Nullable<decimal> CompanyId { get; set; }
    }
}
