//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuantaLabsDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_VCTMonthlyReport
    {
        public Nullable<int> vcttotallessthanfivemale { get; set; }
        public Nullable<int> vcttotallessthanninemale { get; set; }
        public Nullable<int> vcttotallessthanfourteenmale { get; set; }
        public Nullable<int> vcttotallessthanninteenmale { get; set; }
        public Nullable<int> vcttotallessthantwentyfourmale { get; set; }
        public Nullable<int> vcttotallessthantewntyninemale { get; set; }
        public Nullable<int> vcttotallessthanfourtyninemale { get; set; }
        public Nullable<int> vcttotalgreaterthanfiftymale { get; set; }
        public Nullable<int> vctinitialreactivelessfivemale { get; set; }
        public Nullable<int> vctinitialreactivelessninemale { get; set; }
        public Nullable<int> vctinitialreactivelessfourteenmale { get; set; }
        public Nullable<int> vctinitialreactivelessninteenmale { get; set; }
        public Nullable<int> vctinitialreactivelesstwentyfourmale { get; set; }
        public Nullable<int> vctinitialreactivelesstwentyninemale { get; set; }
        public Nullable<int> vctinitialreactivelessfourtyninemale { get; set; }
        public Nullable<int> vctinitialreactivegreaterfiftymale { get; set; }
        public int vctpositivelessthanfivemale { get; set; }
        public int vctpositivelessthanninemale { get; set; }
        public int vctpositivelessthanfourteenmale { get; set; }
        public int vctpositivelessthanninteenmale { get; set; }
        public int vctpositivelessthantwentyfourmale { get; set; }
        public int vctpositivelessthantwentyninemale { get; set; }
        public int vctpositivelessthanfourtyninemale { get; set; }
        public int vctpositivegreaterthanfiftymale { get; set; }
        public Nullable<int> vcttotallessfivefemale { get; set; }
        public Nullable<int> vcttotallessninefemale { get; set; }
        public Nullable<int> vcttotallessfourteenfemale { get; set; }
        public Nullable<int> vcttotallessninteenfemale { get; set; }
        public Nullable<int> vcttotallesstwentyfourfemale { get; set; }
        public Nullable<int> vcttotallesstwentyninefemale { get; set; }
        public Nullable<int> vcttotallessfourtyninefemale { get; set; }
        public Nullable<int> vcttotalgreaterthanfiftyfemale { get; set; }
        public Nullable<int> vctinitialreactivefemale { get; set; }
        public Nullable<int> vctinitialreactivelessninefemale { get; set; }
        public Nullable<int> vctinitialreactivelessfourteenfemale { get; set; }
        public Nullable<int> vctinitialreactivelessninteenfemale { get; set; }
        public Nullable<int> vctinitialreactivelesstwentyfourfemale { get; set; }
        public Nullable<int> vctinitialreactivelesstwentyninefemale { get; set; }
        public Nullable<int> vctinitialreactivelessfourtyninefemale { get; set; }
        public Nullable<int> vctinitialreactivegreaterthanfiftyfemale { get; set; }
        public Nullable<int> vctpositivefemale { get; set; }
        public Nullable<int> vctpositivelessninefemale { get; set; }
        public Nullable<int> vctpositivelessfourteenfemale { get; set; }
        public Nullable<int> vctpositivelessninteenfemale { get; set; }
        public Nullable<int> vctpositivelesstwentyfourfemale { get; set; }
        public Nullable<int> vctpositivelesstwentyninefemale { get; set; }
        public Nullable<int> vctpositivelessfourtyninefemale { get; set; }
        public Nullable<int> vctpositivegreaterthanfiftyfemale { get; set; }
        public Nullable<decimal> CompanyId { get; set; }
    }
}
