//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabsDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Turn_Around_Times
    {
        public int Id { get; set; }
        public int Test { get; set; }
        public int TTAT_Days { get; set; }
        public int TTAT_Hours { get; set; }
        public int RDD_Days { get; set; }
        public int RDD_Hours { get; set; }
        public Nullable<int> Vial_Type { get; set; }
        public string srno { get; set; }
        public string srno1 { get; set; }
        public Nullable<System.DateTime> CreatedUtc { get; set; }
        public int DepartmentRadPath { get; set; }
        public int BranchId { get; set; }
    
        public virtual LabTest LabTest { get; set; }
        public virtual VialMaster VialMaster { get; set; }
    }
}
