//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabsDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkOrder()
        {
            this.WorkOrderTests = new HashSet<WorkOrderTest>();
        }
    
        public int Id { get; set; }
        public Nullable<int> OPDNo { get; set; }
        public string OPDType { get; set; }
        public int BillPaid { get; set; }
        public int Doctor { get; set; }
        public string LabNo { get; set; }
        public string PathNo { get; set; }
        public Nullable<bool> ShowInSpecimentResultEnty { get; set; }
        public Nullable<bool> ShowInSpecimentCollection { get; set; }
        public int Accession_Status { get; set; }
        public string Financial_Year { get; set; }
        public Nullable<System.DateTime> CreatedUtc { get; set; }
        public int DepartmentRadPath { get; set; }
        public int BranchId { get; set; }
        public string DoctorsNotes { get; set; }
    
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrderTest> WorkOrderTests { get; set; }
    }
}
