//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmbuPharmacyDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMCMaster
    {
        public int srno { get; set; }
        public string providercode { get; set; }
        public string instrumentcode { get; set; }
        public string contactpersonname { get; set; }
        public string contactpersonaddress { get; set; }
        public string contactno { get; set; }
        public Nullable<int> servicereq { get; set; }
        public string servicetype { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<double> discount { get; set; }
        public Nullable<double> billamt { get; set; }
        public Nullable<System.DateTime> AMCstartdate { get; set; }
        public Nullable<System.DateTime> AMCenddate { get; set; }
        public string providername { get; set; }
        public string instrumentname { get; set; }
        public string username { get; set; }
        public Nullable<decimal> companyid { get; set; }
        public string FinancialYearID { get; set; }
        public string serviceReqType { get; set; }
        public string EmailId { get; set; }
        public string ServiceTypes { get; set; }
        public string LocationNo { get; set; }
        public Nullable<int> CategoryID { get; set; }
    }
}
