//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmbuPharmacyDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bom_Main
    {
        public decimal Bom_Mid { get; set; }
        public string TLCode { get; set; }
        public Nullable<double> TotalCost { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string HCode { get; set; }
    }
}
