//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmbuPharmacyDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CleanupRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CleanupRequest()
        {
            this.CleanupRequestTransactions = new HashSet<CleanupRequestTransaction>();
        }
    
        public int RequestId { get; set; }
        public string pepatid { get; set; }
        public string Building { get; set; }
        public string FloorNo { get; set; }
        public string RoomNo { get; set; }
        public Nullable<int> BedNo { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<int> companyid { get; set; }
        public Nullable<decimal> FinancialYearId { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> ProcessFlag { get; set; }
        public string Remark { get; set; }
        public string RequestType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CleanupRequestTransaction> CleanupRequestTransactions { get; set; }
    }
}
