//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmbuPharmacyDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugMaster_old
    {
        public int DrugId { get; set; }
        public string IDA_Code { get; set; }
        public string DrugName { get; set; }
        public Nullable<double> costprice { get; set; }
        public Nullable<decimal> qtyrequired { get; set; }
        public Nullable<double> ReOrderLevel { get; set; }
        public Nullable<int> Mfg_Co_Id { get; set; }
        public Nullable<int> Groupid { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> TDateTime { get; set; }
        public string CompName { get; set; }
        public Nullable<int> G_Drugid { get; set; }
        public string IssueToFlag { get; set; }
        public string StoreFlag { get; set; }
        public Nullable<int> companyid { get; set; }
        public Nullable<int> CasePack { get; set; }
        public string VIP { get; set; }
        public string EXE { get; set; }
        public Nullable<bool> IsConsumable { get; set; }
        public string Notes { get; set; }
        public string TypeFlag { get; set; }
        public Nullable<int> DoseSrNo { get; set; }
        public string Remark { get; set; }
        public string SideEffects { get; set; }
        public string Toxicities { get; set; }
        public string Allergies { get; set; }
        public Nullable<int> RouteofAdmin { get; set; }
        public Nullable<double> ProfitPercent { get; set; }
        public Nullable<int> RackID { get; set; }
        public string CellID { get; set; }
        public string Mfg_Co_Name { get; set; }
        public Nullable<int> UnitID { get; set; }
    }
}
