//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmbuPharmacyDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugExchanage
    {
        public int DrugExchgId { get; set; }
        public Nullable<int> DrugId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> Exchange_ItemId { get; set; }
        public string Item_Description { get; set; }
        public string BatchNo { get; set; }
        public Nullable<System.DateTime> Exp_date { get; set; }
        public Nullable<double> Expired_Qty { get; set; }
        public Nullable<System.DateTime> Exchange_Date { get; set; }
        public Nullable<double> Exchange_Qty { get; set; }
        public Nullable<double> FinancialYearId { get; set; }
        public string IssueToFlag { get; set; }
        public string StoreFlag { get; set; }
        public string companyid { get; set; }
        public Nullable<int> invoiceNo { get; set; }
    }
}
