//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmbuPharmacyDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemStockLedger
    {
        public int TransSrno { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string BatchNo { get; set; }
        public Nullable<int> InvoiceUnit { get; set; }
        public Nullable<int> BillTransUnit { get; set; }
        public string StoreFlag { get; set; }
        public Nullable<int> companyid { get; set; }
        public Nullable<decimal> wardno { get; set; }
        public string IssueToFlag { get; set; }
    }
}
