//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmbuPharmacyDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT_Schedule
    {
        public int srno { get; set; }
        public Nullable<decimal> OTId { get; set; }
        public Nullable<System.DateTime> Schedule_Date { get; set; }
        public string Schedule_Day { get; set; }
        public string SurgeonName { get; set; }
        public Nullable<int> FinancialYearId { get; set; }
        public int companyid { get; set; }
        public string username { get; set; }
    }
}
