//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmbuPharmacyDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMMaterial
    {
        public int Srno { get; set; }
        public Nullable<int> Partno { get; set; }
        public string PartName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> companyid { get; set; }
        public string Username { get; set; }
        public string FinancialyearId { get; set; }
        public Nullable<int> PMno { get; set; }
    }
}
