//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmbuPharmacyDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ReqForItem
    {
        public int ReqItemId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> RequstedQty { get; set; }
        public string RequestType { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string Requesttime { get; set; }
        public Nullable<System.DateTime> RequiredDate { get; set; }
        public string RequiredTime { get; set; }
        public string StoreFlag { get; set; }
        public string IssueToFlag { get; set; }
        public string FinancialYearID { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string UserName { get; set; }
        public string Remark { get; set; }
        public Nullable<int> CurrentStrileQty { get; set; }
        public string Status { get; set; }
        public Nullable<int> DeptId { get; set; }
        public string NurseName { get; set; }
        public Nullable<int> WardNo { get; set; }
    }
}
