//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmbuPharmacyDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_GRNReturn
    {
        public int GRNRetID { get; set; }
        public Nullable<int> GRNNo { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string Batchno { get; set; }
        public Nullable<int> ReturnQty { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string StoreFlag { get; set; }
        public string IssueToFlag { get; set; }
        public Nullable<int> Companyid { get; set; }
        public Nullable<int> SupplierCode { get; set; }
        public string UserName { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<double> MRP { get; set; }
        public Nullable<double> PCS { get; set; }
        public string CalculationOn { get; set; }
        public Nullable<double> VatRate { get; set; }
        public Nullable<double> TaxAmt { get; set; }
        public string RemarkIfAny { get; set; }
        public Nullable<double> TotalAmt { get; set; }
        public Nullable<bool> CreditNote { get; set; }
        public Nullable<double> DiscountPer { get; set; }
        public Nullable<double> NetAmt { get; set; }
        public Nullable<double> AmountPaid { get; set; }
        public Nullable<double> Balance { get; set; }
    }
}
