//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmbuPharmacyDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SubPack
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_SubPack()
        {
            this.Tbl_RequestForPack = new HashSet<Tbl_RequestForPack>();
        }
    
        public int PackTranID { get; set; }
        public Nullable<int> SubPackID { get; set; }
        public Nullable<int> PackageID { get; set; }
        public string StoreFlag { get; set; }
        public string IssueToFlag { get; set; }
        public string FinancialYearID { get; set; }
        public string Username { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<bool> PTransFlag { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
        public Nullable<bool> AcceptFlag { get; set; }
        public Nullable<bool> SterileFlag { get; set; }
        public Nullable<bool> RequestFlag { get; set; }
        public string Status { get; set; }
        public Nullable<bool> MissingFlag { get; set; }
        public string ExpiryDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RequestForPack> Tbl_RequestForPack { get; set; }
    }
}
