//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmbuPharmacyDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_IssueSetToPatient
    {
        public int IssueId { get; set; }
        public string PatientType { get; set; }
        public string PePatID { get; set; }
        public string ItemSetType { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> PackageID { get; set; }
        public Nullable<int> SubPackID { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string StoreFlag { get; set; }
        public string IssueToFlag { get; set; }
        public string FinancialYearID { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> NDept { get; set; }
    }
}
