//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmbuPharmacyDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tmp_VaccineReport
    {
        public int Id { get; set; }
        public string DrugName { get; set; }
        public Nullable<int> A_OPStock { get; set; }
        public Nullable<int> B_RecQty { get; set; }
        public Nullable<int> C_TotDosAB { get; set; }
        public Nullable<int> D_ClosingStock { get; set; }
        public Nullable<int> E_IssueQty { get; set; }
        public Nullable<int> F_NoofChildern { get; set; }
        public Nullable<int> G_DoseWastedEF { get; set; }
        public Nullable<int> Companyid { get; set; }
        public string Month { get; set; }
        public Nullable<int> DrugId { get; set; }
        public string Year { get; set; }
    }
}
