//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmbuPharmacyDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkTypeMaster
    {
        public int WorkTypeNo { get; set; }
        public string WorkType { get; set; }
        public string Description { get; set; }
        public Nullable<int> companyid { get; set; }
        public string Username { get; set; }
        public string FinancialyearId { get; set; }
    }
}
