//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaresoftHMISDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allergy
    {
        public int Id { get; set; }
        public int OPDno { get; set; }
        public int UserId { get; set; }
        public int BranchId { get; set; }
        public string AllergicFoodType { get; set; }
        public string ItemName { get; set; }
        public string AllergyName { get; set; }
        public Nullable<int> Since { get; set; }
        public string SinceUnit { get; set; }
        public string SignsAndSymptoms { get; set; }
        public string Severity { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual OpdRegister OpdRegister { get; set; }
    }
}
