//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaresoftHMISDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodBankDonorInformation
    {
        public int Id { get; set; }
        public int user { get; set; }
        public System.DateTime DateStamp { get; set; }
        public string Salutation { get; set; }
        public string DonorName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public Nullable<int> PinCode { get; set; }
        public Nullable<System.DateTime> MarriageAnniversary { get; set; }
        public string ContactNo { get; set; }
        public string MobileNo { get; set; }
        public string Occassion { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public int Age { get; set; }
        public string Sex { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<int> NoPreviousDonations { get; set; }
        public Nullable<System.DateTime> DonationDate { get; set; }
        public Nullable<System.TimeSpan> DonationTime { get; set; }
        public Nullable<System.DateTime> LastDonationDate { get; set; }
        public Nullable<int> CardNo { get; set; }
        public string DonationType { get; set; }
        public string BloodBagType { get; set; }
        public Nullable<int> Qty { get; set; }
        public string BatchNo { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string MfgCompany { get; set; }
        public string MedicalOfficer { get; set; }
        public int Weight { get; set; }
        public Nullable<int> Height { get; set; }
        public string Pulse { get; set; }
        public string HB { get; set; }
        public string BP { get; set; }
        public string Temp { get; set; }
        public string VSite { get; set; }
        public string CVS { get; set; }
        public string RS { get; set; }
        public string CNS { get; set; }
        public string PA { get; set; }
    }
}
