//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaresoftHMISDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodBankCampInformation
    {
        public int Id { get; set; }
        public System.DateTime DateEntered { get; set; }
        public int user { get; set; }
        public string OrgName { get; set; }
        public string Occassion { get; set; }
        public string Address { get; set; }
        public string SiteAddress { get; set; }
        public string CampIncharge { get; set; }
        public string OrgPhoneNo { get; set; }
        public int ExpectedDonors { get; set; }
        public string PhoneNo { get; set; }
        public int NoMales { get; set; }
        public int NoFemales { get; set; }
        public System.DateTime CampDate { get; set; }
        public System.TimeSpan CampTime { get; set; }
        public string Area { get; set; }
        public string Facility { get; set; }
        public string Hygiene { get; set; }
        public string Furniture { get; set; }
        public string Cleanliness { get; set; }
        public string Communication { get; set; }
        public string ElectricSupply { get; set; }
        public string RefreshmentFacility { get; set; }
        public string AdequateLighting { get; set; }
        public string Handwashing { get; set; }
        public string WasteDisposal { get; set; }
        public Nullable<int> TotalBeds { get; set; }
    }
}
