//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaresoftHMISDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodBankMasterSetting
    {
        public int Id { get; set; }
        public int User { get; set; }
        public System.DateTime DateTimeStamp { get; set; }
        public string BloodTypeCode { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public string MfgCompany { get; set; }
        public int ExpiryDays { get; set; }
        public string SuffixCode { get; set; }
        public int Rate { get; set; }
    }
}
