//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaresoftHMISDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CaresoftHMISEntities : DbContext
    {
        public CaresoftHMISEntities()
            : base("name=CaresoftHMISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdmissionRecommendation> AdmissionRecommendations { get; set; }
        public virtual DbSet<AmbulanceMaster> AmbulanceMasters { get; set; }
        public virtual DbSet<AmbulanceRequest> AmbulanceRequests { get; set; }
        public virtual DbSet<AMCMaster> AMCMasters { get; set; }
        public virtual DbSet<AssignmentDetail> AssignmentDetails { get; set; }
        public virtual DbSet<BillAdjustmentLog> BillAdjustmentLogs { get; set; }
        public virtual DbSet<BillPayment> BillPayments { get; set; }
        public virtual DbSet<BillService> BillServices { get; set; }
        public virtual DbSet<BloodBankBloodComponet> BloodBankBloodComponets { get; set; }
        public virtual DbSet<BloodBankBloodTest> BloodBankBloodTests { get; set; }
        public virtual DbSet<BloodBankCampInformation> BloodBankCampInformations { get; set; }
        public virtual DbSet<BloodBankCampOrganizer> BloodBankCampOrganizers { get; set; }
        public virtual DbSet<BloodBankDonorBloodBankTest> BloodBankDonorBloodBankTests { get; set; }
        public virtual DbSet<BloodBankDonorBloodGrouping> BloodBankDonorBloodGroupings { get; set; }
        public virtual DbSet<BloodBankDonorInformation> BloodBankDonorInformations { get; set; }
        public virtual DbSet<BloodBankInformation> BloodBankInformations { get; set; }
        public virtual DbSet<BloodBankPatientRequisition> BloodBankPatientRequisitions { get; set; }
        public virtual DbSet<BloodGroup> BloodGroups { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<CashPointReconciliation> CashPointReconciliations { get; set; }
        public virtual DbSet<CleanupRequest> CleanupRequests { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyType> CompanyTypes { get; set; }
        public virtual DbSet<Complaint> Complaints { get; set; }
        public virtual DbSet<CorneaClinicEntry> CorneaClinicEntries { get; set; }
        public virtual DbSet<CSSDIssueToPatient> CSSDIssueToPatients { get; set; }
        public virtual DbSet<CSSDRequest> CSSDRequests { get; set; }
        public virtual DbSet<DashboardIcon> DashboardIcons { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DepartmentType> DepartmentTypes { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<Diagnosis1s> Diagnosis1s { get; set; }
        public virtual DbSet<Diagnosis2s> Diagnosis2s { get; set; }
        public virtual DbSet<Diagnosis3s> Diagnosis3s { get; set; }
        public virtual DbSet<DischargeRecommendation> DischargeRecommendations { get; set; }
        public virtual DbSet<Disease> Diseases { get; set; }
        public virtual DbSet<DoctorNote> DoctorNotes { get; set; }
        public virtual DbSet<DoctorsSchedule> DoctorsSchedules { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EWallet> EWallets { get; set; }
        public virtual DbSet<FamilyHealthOverview> FamilyHealthOverviews { get; set; }
        public virtual DbSet<FamilyMedicalHistoryQuestion> FamilyMedicalHistoryQuestions { get; set; }
        public virtual DbSet<FamilyMedicalHistoryRespons> FamilyMedicalHistoryResponses { get; set; }
        public virtual DbSet<FieldMeta> FieldMetas { get; set; }
        public virtual DbSet<FinanceBanking> FinanceBankings { get; set; }
        public virtual DbSet<FinanceBank> FinanceBanks { get; set; }
        public virtual DbSet<FinanceCashPointReconciliation> FinanceCashPointReconciliations { get; set; }
        public virtual DbSet<FinanceComfirmBanking> FinanceComfirmBankings { get; set; }
        public virtual DbSet<FinanceDirectBanking> FinanceDirectBankings { get; set; }
        public virtual DbSet<FreeFormMarkup> FreeFormMarkups { get; set; }
        public virtual DbSet<FreeFormMarkupType> FreeFormMarkupTypes { get; set; }
        public virtual DbSet<FreeForm> FreeForms { get; set; }
        public virtual DbSet<FreeFormSelectOption> FreeFormSelectOptions { get; set; }
        public virtual DbSet<GroupRight> GroupRights { get; set; }
        public virtual DbSet<HSBed> HSBeds { get; set; }
        public virtual DbSet<HSBuilding> HSBuildings { get; set; }
        public virtual DbSet<HSFloor> HSFloors { get; set; }
        public virtual DbSet<HSWardCategory> HSWardCategories { get; set; }
        public virtual DbSet<HSWard> HSWards { get; set; }
        public virtual DbSet<IdentificationType> IdentificationTypes { get; set; }
        public virtual DbSet<ImmunizationAdmin> ImmunizationAdmins { get; set; }
        public virtual DbSet<ImmunizationCategory> ImmunizationCategories { get; set; }
        public virtual DbSet<ImmunizationMaster> ImmunizationMasters { get; set; }
        public virtual DbSet<ImmunizationType> ImmunizationTypes { get; set; }
        public virtual DbSet<InsuranceCard> InsuranceCards { get; set; }
        public virtual DbSet<InsuranceInvoice> InsuranceInvoices { get; set; }
        public virtual DbSet<InsurancePrice> InsurancePrices { get; set; }
        public virtual DbSet<InvoiceServiceAllocation> InvoiceServiceAllocations { get; set; }
        public virtual DbSet<IPDBillPartialPayment> IPDBillPartialPayments { get; set; }
        public virtual DbSet<ItemName> ItemNames { get; set; }
        public virtual DbSet<JPayAutoPayment> JPayAutoPayments { get; set; }
        public virtual DbSet<JPayment> JPayments { get; set; }
        public virtual DbSet<KeyValuePair> KeyValuePairs { get; set; }
        public virtual DbSet<LinenRequest> LinenRequests { get; set; }
        public virtual DbSet<MaintenaceWorkType> MaintenaceWorkTypes { get; set; }
        public virtual DbSet<MaintenanceAssignment> MaintenanceAssignments { get; set; }
        public virtual DbSet<MaintenancePMMaster> MaintenancePMMasters { get; set; }
        public virtual DbSet<MaintenanceRequest> MaintenanceRequests { get; set; }
        public virtual DbSet<MaintenanceScheduling> MaintenanceSchedulings { get; set; }
        public virtual DbSet<MaintenceWorkTrade> MaintenceWorkTrades { get; set; }
        public virtual DbSet<MaritalStatu> MaritalStatus { get; set; }
        public virtual DbSet<MasterContraceptive> MasterContraceptives { get; set; }
        public virtual DbSet<MasterPostNatalTest> MasterPostNatalTests { get; set; }
        public virtual DbSet<MCHAntenatalProfile> MCHAntenatalProfiles { get; set; }
        public virtual DbSet<MCHBabyPostNatalEXam> MCHBabyPostNatalEXams { get; set; }
        public virtual DbSet<MCHCancerScreening> MCHCancerScreenings { get; set; }
        public virtual DbSet<MCHClinicalNote> MCHClinicalNotes { get; set; }
        public virtual DbSet<MCHDelivery> MCHDeliveries { get; set; }
        public virtual DbSet<MCHFamilyPlaning> MCHFamilyPlanings { get; set; }
        public virtual DbSet<MCHMaternalProfile> MCHMaternalProfiles { get; set; }
        public virtual DbSet<MCHMedicalAndSergicalHistory> MCHMedicalAndSergicalHistories { get; set; }
        public virtual DbSet<MCHMotherPostNatalExam> MCHMotherPostNatalExams { get; set; }
        public virtual DbSet<MCHPhysicalExamination> MCHPhysicalExaminations { get; set; }
        public virtual DbSet<MCHPresentPregnancy> MCHPresentPregnancies { get; set; }
        public virtual DbSet<MCHPreventativeService> MCHPreventativeServices { get; set; }
        public virtual DbSet<MCHPreventativeService1> MCHPreventativeServices1 { get; set; }
        public virtual DbSet<MCHPreviousPregnancy> MCHPreviousPregnancies { get; set; }
        public virtual DbSet<MCHWeightGainChart> MCHWeightGainCharts { get; set; }
        public virtual DbSet<MealType> MealTypes { get; set; }
        public virtual DbSet<MedicalAdministrationEntry> MedicalAdministrationEntries { get; set; }
        public virtual DbSet<MedicalHistoryQuestion> MedicalHistoryQuestions { get; set; }
        public virtual DbSet<MedicalHistoryRespons> MedicalHistoryResponses { get; set; }
        public virtual DbSet<MedicationFrequency> MedicationFrequencies { get; set; }
        public virtual DbSet<Medication> Medications { get; set; }
        public virtual DbSet<MorgAdmission> MorgAdmissions { get; set; }
        public virtual DbSet<MorgCabinet> MorgCabinets { get; set; }
        public virtual DbSet<MorgColdroom> MorgColdrooms { get; set; }
        public virtual DbSet<NurseTheatreRequest> NurseTheatreRequests { get; set; }
        public virtual DbSet<NutritionAdultRegister> NutritionAdultRegisters { get; set; }
        public virtual DbSet<NutritionChildRegister> NutritionChildRegisters { get; set; }
        public virtual DbSet<NutritionDietchart> NutritionDietcharts { get; set; }
        public virtual DbSet<NutritionScreeningDetail> NutritionScreeningDetails { get; set; }
        public virtual DbSet<OpdRegister> OpdRegisters { get; set; }
        public virtual DbSet<OutsideTest> OutsideTests { get; set; }
        public virtual DbSet<PatientAllergy> PatientAllergies { get; set; }
        public virtual DbSet<PatientAppointment> PatientAppointments { get; set; }
        public virtual DbSet<PatientDiagnosi> PatientDiagnosis { get; set; }
        public virtual DbSet<PatientReferal> PatientReferals { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<PatientTurnAroundTime> PatientTurnAroundTimes { get; set; }
        public virtual DbSet<PaymentMode> PaymentModes { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<PhysicalExamination> PhysicalExaminations { get; set; }
        public virtual DbSet<QuestionnaireMultichoice> QuestionnaireMultichoices { get; set; }
        public virtual DbSet<QuestionnaireQuize> QuestionnaireQuizes { get; set; }
        public virtual DbSet<QuestionnaireRespons> QuestionnaireResponses { get; set; }
        public virtual DbSet<QuestionnaireResponseType> QuestionnaireResponseTypes { get; set; }
        public virtual DbSet<Questionnaire> Questionnaires { get; set; }
        public virtual DbSet<Rebate> Rebates { get; set; }
        public virtual DbSet<RefundedItem> RefundedItems { get; set; }
        public virtual DbSet<Refund> Refunds { get; set; }
        public virtual DbSet<RegularComplaint> RegularComplaints { get; set; }
        public virtual DbSet<Relationship> Relationships { get; set; }
        public virtual DbSet<Religion> Religions { get; set; }
        public virtual DbSet<RenalDialysisInfo> RenalDialysisInfoes { get; set; }
        public virtual DbSet<RenalDialysisOrder> RenalDialysisOrders { get; set; }
        public virtual DbSet<RenalMachineCheck> RenalMachineChecks { get; set; }
        public virtual DbSet<RenalPatientProfile> RenalPatientProfiles { get; set; }
        public virtual DbSet<RenalPostDialysisObservation> RenalPostDialysisObservations { get; set; }
        public virtual DbSet<RightsAllocation> RightsAllocations { get; set; }
        public virtual DbSet<RoleRight> RoleRights { get; set; }
        public virtual DbSet<RoleRightsAction> RoleRightsActions { get; set; }
        public virtual DbSet<RoutingAdmin> RoutingAdmins { get; set; }
        public virtual DbSet<SafetyInstructionMaster> SafetyInstructionMasters { get; set; }
        public virtual DbSet<Salutation> Salutations { get; set; }
        public virtual DbSet<SanctionedAmount> SanctionedAmounts { get; set; }
        public virtual DbSet<ServiceGroup> ServiceGroups { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServicesPrice> ServicesPrices { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<SystemExamCategory> SystemExamCategories { get; set; }
        public virtual DbSet<SystemicExamResult> SystemicExamResults { get; set; }
        public virtual DbSet<SystemRight> SystemRights { get; set; }
        public virtual DbSet<Tariff> Tariffs { get; set; }
        public virtual DbSet<TATLog> TATLogs { get; set; }
        public virtual DbSet<TblController> TblControllers { get; set; }
        public virtual DbSet<TBScreeningQuestion> TBScreeningQuestions { get; set; }
        public virtual DbSet<TBScreeningRespons> TBScreeningResponses { get; set; }
        public virtual DbSet<temp> temps { get; set; }
        public virtual DbSet<TheatreDepartment> TheatreDepartments { get; set; }
        public virtual DbSet<TheatreDesignation> TheatreDesignations { get; set; }
        public virtual DbSet<TheatreOperationPersonel> TheatreOperationPersonels { get; set; }
        public virtual DbSet<TheatrePatientBioData> TheatrePatientBioDatas { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VitalRanx> VitalRanges { get; set; }
        public virtual DbSet<WaiverReason> WaiverReasons { get; set; }
        public virtual DbSet<Waiver> Waivers { get; set; }
        public virtual DbSet<WardTypeCharge> WardTypeCharges { get; set; }
        public virtual DbSet<PatientClaim> PatientClaims { get; set; }
        public virtual DbSet<SystemExamParticular> SystemExamParticulars { get; set; }
        public virtual DbSet<InvoiceBill> InvoiceBills { get; set; }
        public virtual DbSet<InvoiceMedicationBill> InvoiceMedicationBills { get; set; }
        public virtual DbSet<PatientDetail> PatientDetails { get; set; }
        public virtual DbSet<vw_ServiceChatter> vw_ServiceChatter { get; set; }
    }
}
