//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaresoftHMISDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeathCertificate
    {
        public int Id { get; set; }
        public int OPDno { get; set; }
        public int UserId { get; set; }
        public int BranchId { get; set; }
        public string LetterNo { get; set; }
        public string RegNo { get; set; }
        public string DeceasedName { get; set; }
        public int Age { get; set; }
        public string Sex { get; set; }
        public Nullable<System.TimeSpan> DieTime { get; set; }
        public Nullable<System.DateTime> DieDate { get; set; }
        public Nullable<System.DateTime> DeathCause { get; set; }
        public string DeathDiseaseCause { get; set; }
        public Nullable<System.DateTime> From { get; set; }
        public Nullable<System.DateTime> To { get; set; }
        public string AntecedentCause { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string SignificantCauseCondition { get; set; }
        public Nullable<System.DateTime> FromDateCondition { get; set; }
        public Nullable<System.DateTime> ToDateCondition { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual OpdRegister OpdRegister { get; set; }
    }
}
