//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaresoftHMISDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRConfirmation
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int BranchId { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<int> ApplicantId { get; set; }
        public Nullable<int> Level1 { get; set; }
        public string InstitutionName { get; set; }
        public string ContactedPerson { get; set; }
        public Nullable<System.DateTime> DateConfirmed { get; set; }
        public string Reviewer { get; set; }
        public string ResultsObtained { get; set; }
        public string Remarks { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Instiution { get; set; }
        public string Telephone { get; set; }
        public string PostalAddress { get; set; }
        public string ResultsObtained1 { get; set; }
        public string Remarks1 { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
