//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaresoftHMISDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRJobRequisition
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int BranchId { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<decimal> RequisitionNo { get; set; }
        public string RequistionType { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> RequisitionDate { get; set; }
        public Nullable<System.DateTime> DateDue { get; set; }
        public string JobCategory { get; set; }
        public string PositionOrTitle { get; set; }
        public string HiringAuthority { get; set; }
        public string Education { get; set; }
        public string SkillsOrExperience { get; set; }
    }
}
