//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaresoftHMISDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRUnionDeregistration
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int BranchId { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<int> UnionId { get; set; }
        public Nullable<bool> DeregisterStaff { get; set; }
        public Nullable<int> StaffId { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> DateOfDeregistration { get; set; }
        public string DeregisteringAuthority { get; set; }
        public string CommentOnDeregistrationReasons { get; set; }
    }
}
