//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaresoftHMISDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceAssignment
    {
        public int Id { get; set; }
        public string AssignedWorker { get; set; }
        public string RequsetedTask { get; set; }
        public System.DateTime AllocatedDate { get; set; }
        public System.TimeSpan AllocatedTime { get; set; }
        public bool Status { get; set; }
        public int UserId { get; set; }
        public int BranchId { get; set; }
        public System.DateTime AddedOn { get; set; }
    }
}
