//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaresoftHMISDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCHAdmissionExamination
    {
        public int Id { get; set; }
        public int OPDNo { get; set; }
        public int BranchId { get; set; }
        public int UserId { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<int> FudusHeight { get; set; }
        public string Urine { get; set; }
        public Nullable<int> Height { get; set; }
        public string VerginalDischarge { get; set; }
        public string Presentation { get; set; }
        public string ExtGenital { get; set; }
        public int Weight { get; set; }
        public string Engagement { get; set; }
        public string HB { get; set; }
        public string Spleen { get; set; }
        public string Position { get; set; }
        public string BP { get; set; }
        public string Abnomalities { get; set; }
        public string FoetalHeart { get; set; }
        public Nullable<int> Temperature { get; set; }
        public string Pulse { get; set; }
        public string Respiratory { get; set; }
    
        public virtual OpdRegister OpdRegister { get; set; }
    }
}
