//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaresoftHMISDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCHPreviousPregnancy
    {
        public int Id { get; set; }
        public int OPDNo { get; set; }
        public Nullable<int> NumberOfANCAttended { get; set; }
        public string PlaceOfDelivery { get; set; }
        public string Maturity { get; set; }
        public string TypeOfDelivery { get; set; }
        public string BirthWeight { get; set; }
        public string Gender { get; set; }
        public string Outcome { get; set; }
        public string Puerperium { get; set; }
        public int UserId { get; set; }
        public int BranchId { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string Year_ { get; set; }
        public string PregnancyOrder { get; set; }
        public string DurationOfLabour { get; set; }
    
        public virtual OpdRegister OpdRegister { get; set; }
        public virtual User User { get; set; }
    }
}
