//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaresoftHMISDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NurseStationVoucher
    {
        public int VoucherNO { get; set; }
        public string RequestingStation { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<decimal> Total { get; set; }
        public bool IsItemIssued { get; set; }
    }
}
