//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaresoftHMISDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientClaim
    {
        public int Id { get; set; }
        public int OPDId { get; set; }
        public string ClaimNumber { get; set; }
        public int UserId { get; set; }
        public int BrunchId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual OpdRegister OpdRegister { get; set; }
        public virtual User User { get; set; }
    }
}
