//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaresoftHMISDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_2
    {
        public System.DateTime Timestap { get; set; }
        public int DoctorId { get; set; }
        public int OpdIpdNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string RegNumber { get; set; }
        public string Salutation { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string LName { get; set; }
    }
}
